### ISSUE TITLE
大佬，请问有原版加照片修复的项目代码吗，谢谢

### ISSUE THREAD

**Issue by cqmyg123** [RainFZY/IQA-and-Distortion-Classification-System#1]

**Comment by RainFZY** [comment]
提供一下你的联系方式？

**Comment by cqmyg123** [comment]
mzlyt1999@gmail.com     谢谢大佬

**Comment by cqmyg123** [comment]
请问这个是无参考还是半参考类型，谢谢

**Comment by RainFZY** [comment]
> 请问这个是无参考还是半参考类型，谢谢

是无参考的

**Comment by RainFZY** [comment]
> [mzlyt1999@gmail.com](mailto:mzlyt1999@gmail.com) 谢谢大佬

给你发过去了

**Comment by RainFZY** [comment]
> [mzlyt1999@gmail.com](mailto:mzlyt1999@gmail.com) 谢谢大佬
我发的邮件被退回来了，你如果还需要、方便的话可以提供一下wechat

**Comment by cqmyg123** [comment]
13923181261大佬如果有谷歌云分享也可以，谢谢解答

**Comment by RainFZY** [comment]
> 13923181261大佬如果有谷歌云分享也可以，谢谢解答

谷歌云发你邮箱了哈

**Comment by cqmyg123** [comment]
> > 13923181261大佬如果有谷歌云分享也可以，谢谢解答
> 
> 谷歌云发你邮箱了哈
收到了，谢谢大佬

**Comment by cqmyg123** [comment]
> > [mzlyt1999@gmail.com](mailto:mzlyt1999@gmail.com)谢谢大佬
> > 我发的邮件被退回来了，你如果还需要，方便的话可以提供一下wechat
